# -*- coding: utf-8 -*-
"""Sawera_lab2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10PdZtfo5Z5y-QtOE5tXAwdipusgGaoGH
"""

!pip install -U google-genai
from google import genai
client = genai.Client(api_key="AQ.Ab8RN6JZnA5i_v7B2c3Q0cXBw34OWwu8DJo5oHualtHl9r_1Hw")
MODEL = "models/gemini-3.6-flash"

response = client.models.generate_content(
    model="models/gemini-3.6-flash",
    contents="Hello"
)

print(response.text)

while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit", "bye"]:
        print("Chatbot: Goodbye 👋")
        break

    response = client.models.generate_content(
        model="models/gemini-3.6-flash",
        contents=user_input
    )

    print("Chatbot:", response.text)